import { Link } from "wouter";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { SEO } from "@/components/seo";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <SEO
        title="Terms of Service"
        canonical="/terms"
        description="The terms that govern your use of TheSocialPundit."
      />
      <SiteHeader />
      <main className="flex-1">
        <article className="py-16 lg:py-24" data-testid="section-terms">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 className="heading-display mb-4" data-testid="text-terms-title">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground mb-12">Last updated: August 28, 2026</p>

            <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
              <section>
                <p className="text-muted-foreground">
                  These Terms of Service ("Terms") govern your access to and use of TheSocialPundit (the
                  "Service"). By creating an account or using the Service, you agree to these Terms. If you
                  don't agree, please don't use the Service.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">What the Service does</h2>
                <p className="text-muted-foreground">
                  TheSocialPundit curates industry news and uses AI to draft social media posts in your
                  voice. LinkedIn and Twitter/X support direct account connection for streamlined posting.
                  For the other supported platforms, the Service generates a ready-to-post draft that you
                  copy and publish yourself, since several of those platforms don't offer a public API for
                  third-party publishing. You always review a draft before it's used — the Service does not
                  publish on your behalf without your action.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Your account</h2>
                <ul className="text-muted-foreground space-y-2">
                  <li>You must provide accurate information when creating your account.</li>
                  <li>You're responsible for maintaining the security of your account credentials.</li>
                  <li>You must be at least 16 years old to use the Service.</li>
                  <li>One account per individual; accounts may not be shared or transferred.</li>
                </ul>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">AI-generated content</h2>
                <p className="text-muted-foreground">
                  Drafts produced by the Service are generated by AI based on real news articles and your
                  chosen tone. AI-generated content can occasionally be inaccurate or require editing. You
                  are solely responsible for reviewing, editing, and approving any content before you publish
                  it under your name, and for ensuring it complies with the rules of whichever platform you
                  post it to.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Acceptable use</h2>
                <p className="text-muted-foreground">You agree not to use the Service to:</p>
                <ul className="text-muted-foreground space-y-2">
                  <li>Publish unlawful, defamatory, harassing, or infringing content.</li>
                  <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service.</li>
                  <li>Use the Service to generate spam or mass unsolicited content.</li>
                  <li>Misrepresent your identity or impersonate another person or organization.</li>
                </ul>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Pricing</h2>
                <p className="text-muted-foreground">
                  The Service is currently offered free to our first 1,000 subscribers. We'll provide
                  reasonable advance notice before introducing paid plans or changing pricing for existing
                  accounts.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Ownership</h2>
                <p className="text-muted-foreground">
                  You own the content you create and publish using the Service. We retain ownership of the
                  Service itself, including our software, design, and branding. You grant us a limited
                  license to process your content solely to provide the Service to you (for example, sending
                  article text to our AI provider to generate your draft).
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Third-party platforms</h2>
                <p className="text-muted-foreground">
                  We are not responsible for the availability, policies, or terms of third-party platforms
                  (such as LinkedIn, Twitter/X, Reddit, or Mastodon) that you choose to publish to. Your use
                  of those platforms is governed by their own terms.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Termination</h2>
                <p className="text-muted-foreground">
                  We may suspend or terminate your access to the Service if you violate these Terms. You may
                  stop using the Service and request account deletion at any time.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Disclaimers and limitation of liability</h2>
                <p className="text-muted-foreground">
                  The Service is provided "as is" without warranties of any kind. We do not guarantee that
                  AI-generated content will be error-free or achieve any particular result. To the fullest
                  extent permitted by law, TheSocialPundit is not liable for indirect, incidental, or
                  consequential damages arising from your use of the Service.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Changes to these Terms</h2>
                <p className="text-muted-foreground">
                  We may update these Terms from time to time. We'll update the "Last updated" date above,
                  and for material changes, we'll make reasonable efforts to notify you directly. Continued
                  use of the Service after changes take effect constitutes acceptance of the new Terms.
                </p>
              </section>

              <section>
                <h2 className="heading-section !text-2xl">Contact us</h2>
                <p className="text-muted-foreground">
                  Questions about these Terms? Reach us at{" "}
                  <a href="mailto:hello@thesocialpundit.com" className="text-primary underline">
                    hello@thesocialpundit.com
                  </a>{" "}
                  or visit our{" "}
                  <Link href="/contact" className="text-primary underline">
                    Contact page
                  </Link>
                  .
                </p>
              </section>
            </div>
          </div>
        </article>
      </main>
      <SiteFooter />
    </div>
  );
}
