// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bold-ink/Dashboard.tsx": () => import("../components/mockups/bold-ink/Dashboard.tsx"),
  "./components/mockups/bold-ink/Landing.tsx": () => import("../components/mockups/bold-ink/Landing.tsx"),
  "./components/mockups/bold-ink/PostModal.tsx": () => import("../components/mockups/bold-ink/PostModal.tsx")
};
